# Generated by Django 4.2.7 on 2024-12-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0002_respuesta_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='parent',
        ),
    ]
