# Generated by Django 4.2.7 on 2024-12-11 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0003_remove_respuesta_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respuesta',
            old_name='usuario',
            new_name='autor',
        ),
    ]
